import com.alibaba.fastjson.JSONObject;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import constant.FileConstant;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class ViewWebInterface {
    private JFrame frame;
    private JPanel panel1;
    private JTextField titleTextField;
    private JTextField userNameTextField;
    private JTextField mailBoxTextField;
    private JTextField passwordTextField;
    private JTextArea remarkTextArea;
    private JButton deleteButton;
    private JButton editButton;

    private MainInterface mainInterface;
    private JSONObject webJson;
    private ViewWebInterfaceActionListener actionListener;

    public ViewWebInterface(MainInterface mainInterface, JSONObject webJson) {
        this.mainInterface = mainInterface;
        this.webJson = webJson;

        actionListener = new ViewWebInterfaceActionListener();
        deleteButton.addActionListener(actionListener);
        editButton.addActionListener(actionListener);
    }

    public void init() {
        frame = new JFrame("NewWebInterface");
        frame.setContentPane(panel1);
        frame.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);

        titleTextField.setText(webJson.getString(FileConstant.JSON_ALL_KEY_NAME_TITLE));
        userNameTextField.setText(webJson.getString(FileConstant.JSON_WEB_KEY_NAME_USER_NAME));
        mailBoxTextField.setText(webJson.getString(FileConstant.JSON_WEB_KEY_NAME_MAIL_BOX));
        passwordTextField.setText(webJson.getString(FileConstant.JSON_WEB_KEY_NAME_PASSWORD));
        remarkTextArea.setText(webJson.getString(FileConstant.JSON_WEB_KEY_NAME_REMARK));
    }

    public class ViewWebInterfaceActionListener implements ActionListener {
        public void actionPerformed(ActionEvent e) {
            if (e.getActionCommand().equals("Delete")) {
                JSONObject allWebJson = ViewWebInterface.this.mainInterface.getAllWebJson();
                if (allWebJson.containsKey(webJson.getString(FileConstant.JSON_ALL_KEY_NAME_TITLE))) {
                    allWebJson.remove(webJson.getString(FileConstant.JSON_ALL_KEY_NAME_TITLE));
                }
                ViewWebInterface.this.frame.dispose();
                ViewWebInterface.this.mainInterface.getViewWebMenuItem().doClick();
                return;
            }

            if (e.getActionCommand().equals("Edit")) {
                String userName = ViewWebInterface.this.userNameTextField.getText();
                String mailBox = ViewWebInterface.this.mailBoxTextField.getText();
                String password = ViewWebInterface.this.passwordTextField.getText();
                String remark = ViewWebInterface.this.remarkTextArea.getText();

                JSONObject allWebJson = ViewWebInterface.this.mainInterface.getAllWebJson();
                if (allWebJson.containsKey(webJson.getString(FileConstant.JSON_ALL_KEY_NAME_TITLE))) {
                    JSONObject editWebJson = allWebJson.getJSONObject(webJson.getString(FileConstant.JSON_ALL_KEY_NAME_TITLE));
                    editWebJson.put(FileConstant.JSON_WEB_KEY_NAME_USER_NAME, userName);
                    editWebJson.put(FileConstant.JSON_WEB_KEY_NAME_MAIL_BOX, mailBox);
                    editWebJson.put(FileConstant.JSON_WEB_KEY_NAME_PASSWORD, password);
                    editWebJson.put(FileConstant.JSON_WEB_KEY_NAME_REMARK, remark);
                }
                ViewWebInterface.this.frame.dispose();
                ViewWebInterface.this.mainInterface.getViewWebMenuItem().doClick();
                return;
            }
        }
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(6, 2, new Insets(0, 0, 0, 0), -1, -1));
        final JLabel label1 = new JLabel();
        label1.setText("Title");
        panel1.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 1, false));
        titleTextField = new JTextField();
        titleTextField.setEditable(false);
        panel1.add(titleTextField, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("UserName");
        panel1.add(label2, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 1, false));
        userNameTextField = new JTextField();
        panel1.add(userNameTextField, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JLabel label3 = new JLabel();
        label3.setText("MailBox");
        panel1.add(label3, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 1, false));
        mailBoxTextField = new JTextField();
        panel1.add(mailBoxTextField, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JLabel label4 = new JLabel();
        label4.setText("Password");
        panel1.add(label4, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 1, false));
        passwordTextField = new JTextField();
        panel1.add(passwordTextField, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JLabel label5 = new JLabel();
        label5.setText("Remark");
        panel1.add(label5, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_NORTHWEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 1, false));
        final JScrollPane scrollPane1 = new JScrollPane();
        panel1.add(scrollPane1, new GridConstraints(4, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(250, 150), null, 0, false));
        remarkTextArea = new JTextArea();
        scrollPane1.setViewportView(remarkTextArea);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        panel1.add(panel2, new GridConstraints(5, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        deleteButton = new JButton();
        deleteButton.setText("Delete");
        panel2.add(deleteButton, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        editButton = new JButton();
        editButton.setText("Edit");
        panel2.add(editButton, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

}
